Add Max extension method
ShittyLabs/fart pull request #56
Opened 2020-10-06 12:39 UTC by dimitrov-d

2020-10-06 13:21 UTC, jakehamtexas approved these changes, later dismissed
Thanks for your submission!

2020-10-06 13:21 UTC, jakehamtexas commented on lib/src/extension/Max.dart
> +    var max = iterable == null || iterable.isEmpty ? null : iterable.first;
Thank you for your contribution!

Just FYI, your implementation is sound, but there is simpler way build this ternary:

```dart
final isEmpty = iterable?.isEmpty ?? true;
var max =  isEmpty  ? null : iterable.first;
```

I moved the `isEmpty` boolean to a separate line to more easily demonstrate the usage of the [null aware operator](https://medium.com/@thinkdigitalsoftware/null-aware-operators-in-dart-53ffb8ae80bb).

Please consider also creating a unit test for your submission!

2020-10-06 13:22 UTC, jakehamtexas commented
@dimitrov-d 

Please merge or rebase master into your branch so that we may proceed with this PR.

2020-10-07 13:06 UTC, dimitrov-d commented
I've added some additional work based on your previous comments

2020-10-07 13:28 UTC, jakehamtexas commented
Hello @dimitrov-d , thanks for all your hard work on this PR!

I am very glad you added a unit test, because it has brought to light an issue that we appear to be having with your implementation. According to your test output, you cannot apply the `>` operator to an object of type `Object`. This means that your generic parameter `T` is not correctly constrained to types that can be compared with `>`.

Please update your implementation to use a type constraint as with the following example:

```dart
extension MaxFart<T extends num> on Interable<T> {
   // ...
}
```

2020-10-07 13:29 UTC, jakehamtexas requested changes
Please get your tests passing (see earlier comment on how), and then this will be ready to go. You can use the command `pub run test` to test locally before committing and pushing your changes upstream.

2020-10-07 13:33 UTC, dimitrov-d commented
> Please get your tests passing (see earlier comment on how), and then this will be ready to go. You can use the command `pub run test` to test locally before committing and pushing your changes upstream.

Ready to go

2020-10-07 13:34 UTC, jakehamtexas approved these changes

2020-10-07 13:34 UTC, merged

2020-10-07 13:34 UTC, jakehamtexas commented
@dimitrov-d Very nice