Adds `Aggregate` extension method
ShittyLabs/fart pull request #57
Opened 2020-10-12 05:59 UTC by the-pat

Closes #55

2020-10-13 16:21 UTC, jreina commented
Is the plan to create separate methods for each overload? This doesn't cover `TSource Aggregate<TSource>(IEnumerable<TSource>, Func<TSource,TSource,TSource>)`

2020-10-13 18:25 UTC, the-pat commented
@jreina, I think it covers it in a 💩 way.

If you check out [this test](https://github.com/ShittyLabs/fart/pull/57/files#diff-82f90370be361cf5a74de10acdec3e2d3088517a1cbdd4a3e29a0ef64c60037aR38), that case is met. But this has the awkwardness of having the define the `TAccumulate` and `TResult`.

Dart doesn't allow method overloads. The alternative to this 💩 solution is something like `aggregate2` and `aggregate3`. What are the thoughts on that? It would probably have better type safety.

2020-10-13 18:39 UTC, jreina commented
I think having a separate method for the `TSource Aggregate<TSource>(IEnumerable<TSource>, Func<TSource,TSource,TSource>)` called `Aggregate1` is acceptable. It's up to @jakehamtexas but that's what's done in the Haskell prelude and also what DangerLinq is doing

2020-10-14 05:10 UTC, the-pat commented
@jreina, I've separated the aggregate implementation to match the prelude style of "overloading". Thanks for the suggestion, I think this allows for better type safety when using aggregate.

2020-10-14 05:36 UTC, jreina requested changes

2020-10-14 05:36 UTC, jreina commented on test/aggregate_test.dart
> +    group('Success Scenerios', () {
`Scenarios` is misspelled throughout. I'm reading it as "scene-er-ee-o" in Ned Flanders's voice
![image](https://user-images.githubusercontent.com/2089820/95947973-4c94e480-0db5-11eb-8c66-fff19250168e.png)

2020-10-14 09:10 UTC, the-pat commented on test/aggregate_test.dart
> +    group('Success Scenerios', () {
Well this is embarrassing...
![Homer Simpson saying "Doh!"](https://user-images.githubusercontent.com/22896198/95968298-914c6a00-0e0d-11eb-980c-6282b0935860.png)

2020-10-15 10:46 UTC, the-pat commented
@jreina, this is ready to review again.

2020-10-15 14:24 UTC, jreina approved these changes

2020-10-17 18:34 UTC, merged